# Generated by Django 3.1.7 on 2021-03-19 12:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20210319_1732'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('basketapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='basket',
            unique_together={('user', 'product')},
        ),
    ]
